apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
  name: frontend
  namespace: rhsso-openshift-demo
spec:
  clusterIP: 10.217.4.168
  clusterIPs:
  - 10.217.4.168
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
  selector:
    deployment: frontend
